USE bAmazon_db;

insert into items (product_name ,department_name,price , quantity) 
values ('METHANOL','CHEMISTRY', 10, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('ETHANOL','CHEMISTRY', 20, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('PROPANOL','CHEMISTRY', 30, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('BUTANOL','CHEMISTRY', 40, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('PENTANOL','CHEMISTRY', 50, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('L','CHEMISTRY', 60, 200);
insert into items (product_name ,department_name,price , quantity) 
values ('HEXANOL','CHEMISTRY', 70, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('SEPTANOL','CHEMISTRY', 80, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('OCTANOL','CHEMISTRY', 90, 200);

insert into items (product_name ,department_name,price , quantity) 
values ('1-2 DIETHYL ETHER','CHEMISTRY', 90, 200);



SELECT * FROM items;